export PATH=$HOME/bin:$PATH

export ZSH="/Users/thatdevsherry/.oh-my-zsh"

DISABLE_AUTO_TITLE="true"
COMPLETION_WAITING_DOTS="true"

plugins=(git dotenv vi-mode)
source $ZSH/oh-my-zsh.sh
export EDITOR='nvim'
alias cat="bat"
alias cd="z"
alias vim="nvim"
alias vi="nvim"
alias ls="lsd"

export PATH=$HOME/Work/Android/SDK/platform-tools:$PATH
export PATH=$PATH:/usr/local/sbin


[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

eval "$(fnm env --use-on-cd)"
eval "$(zoxide init zsh)"
eval "$(starship init zsh)"
