export PATH=$HOME/bin:/usr/local/bin:$HOME/.local/bin:$PATH
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git vi-mode dotenv)
source $ZSH/oh-my-zsh.sh

# aliases
alias cat="bat"
alias cd="z"
alias ls="lsd"
alias vi="nvim"
alias vim="nvim"

# fnm
export PATH="$HOME/.local/share/fnm:$PATH"
eval "`fnm env`"

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
export PYENV_VIRTUALENV_DISABLE_PROMPT=1
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

# Better cd
eval "$(zoxide init zsh)"

# Better zsh prompt
eval "$(starship init zsh)"

# Work
if [ "$(whoami)" != "thatdevsherry" ]; then
    source $HOME/.abyss.sh
fi
